### ISSUE TITLE
annotationsProcessor configuration is broken

### ISSUE THREAD

**Issue by pmccarren** [ReactNativeBrasil/react-native-sum-up#9]
Hello!

Working to get rn-sumup installed in an Android ReactNative App, however I ran into this error:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:javaPreCompileDebug'.
> Annotation processors must be explicitly declared now.  The following dependencies on the compile classpath are found to contain annotation processor.  Please add them to the annotationProcessor configuration.
    - jetified-argument-1.0.4.jar (com.neenbedankt.bundles:argument:1.0.4)
  Alternatively, set android.defaultConfig.javaCompileOptions.annotationProcessorOptions.includeCompileClasspath = true to continue with previous behavior.  Note that this option is deprecated and will be removed in the future.
  See https://developer.android.com/r/tools/annotation-processor-error-message.html for more details.
```

After removing the below two lines from build.gradle > dependencies, the app builds.

```
annotationProcessor 'com.neenbedankt.bundles:argument:1.0.4'
compile 'com.neenbedankt.bundles:argument:1.0.4'
```

I'm not familiar with Java, nor Android development so I'm not sure if this will break other things. For example, when I call "RNSumup.authenticateWithToken", the app crashes. Perhaps this is a separate issue.

Happy to answer any questions and help in any way I can.

**Comment by ital0** [comment]
Hey @pmccarren. Sorry for the late response.

Depending of the version of React Native that you're using in your project, I'll recommend to use old version of this library. Those new versions was attempts to adapt SumUp SDK to new versions of React Native, but unfornately I can't do it right now. Maybe in a close future... :(

I also recommend you to get some reading about creating bridges for React Native. You don't need very specific knowledge to do, only logics and some web researchs will help you to create your own bridge, specially with SumUp SDK, because they basically give everything ready in your hands.
